,(UsageCode='GOV_DOMAINYSTEM',PK_PickList=5000, DisplayValue='GOV Domain Registration Systems', PK_PicklistType=400, SortOrder=1)
,(UsageCode='ACCESS_DATA_SYS',PK_PickList=5001, DisplayValue='Access to Data systems', PK_PicklistType=400, SortOrder=2)
,(UsageCode='AGENC_SUPPORT_T',PK_PickList=5002, DisplayValue='Agency support tool ', PK_PicklistType=400, SortOrder=3)
,(UsageCode='BUSI_INTELLIG_S',PK_PickList=5003, DisplayValue='Business Intelligence Services', PK_PicklistType=400, SortOrder=4)
,(UsageCode='COLLABOR_TPOINT',PK_PickList=5004, DisplayValue='Collaboration Tools (SharePoint)', PK_PicklistType=400, SortOrder=5)
,(UsageCode='COLLECT_AN_DATA',PK_PickList=5005, DisplayValue='Collect, analyze, maintain and share data', PK_PicklistType=400, SortOrder=6)
,(UsageCode='CONSUL_DATABAS_',PK_PickList=5006, DisplayValue='Consulate Database (VISA)', PK_PicklistType=400, SortOrder=7)
,(UsageCode='CYBERSECUR_MONI',PK_PickList=5007, DisplayValue='Cybersecurity Monitoring', PK_PicklistType=400, SortOrder=8)
,(UsageCode='CYBERSECURSOLUT',PK_PickList=5008, DisplayValue='Cybersecurity tools/solutions', PK_PicklistType=400, SortOrder=9)
,(UsageCode='DATA_REPOSITORI',PK_PickList=5009, DisplayValue='Data Repository', PK_PicklistType=400, SortOrder=10)
,(UsageCode='DECIS_MAKE_TOOL',PK_PickList=5010, DisplayValue='Decision making tool', PK_PicklistType=400, SortOrder=11)
,(UsageCode='DIPLOMAT_IOMMUN',PK_PickList=5011, DisplayValue='Diplomatic and Incident Response Communications', PK_PicklistType=400, SortOrder=12)
,(UsageCode='EMAIL_SERVCCESS',PK_PickList=5012, DisplayValue='Email services and/or internet access', PK_PicklistType=400, SortOrder=13)
,(UsageCode='EMERG_MANAG_SYS',PK_PickList=5013, DisplayValue='Emergency management System', PK_PicklistType=400, SortOrder=14)
,(UsageCode='EMERG_RESPONNEL',PK_PickList=5014, DisplayValue='Emergency response plans and personnel', PK_PicklistType=400, SortOrder=15)
,(UsageCode='ENTERPRIS__PLAN',PK_PickList=5015, DisplayValue='Enterprise resource planning', PK_PicklistType=400, SortOrder=16)
,(UsageCode='EXPLOS_THREAT_P',PK_PickList=5016, DisplayValue='Explosive Threat Profiles', PK_PicklistType=400, SortOrder=17)
,(UsageCode='FINANCI_AGENC_L',PK_PickList=5017, DisplayValue='Financial [Agency Level]', PK_PicklistType=400, SortOrder=18)
,(UsageCode='FINANCI_NATION_',PK_PickList=5018, DisplayValue='Financial [National Level]', PK_PicklistType=400, SortOrder=19)
,(UsageCode='FINANCI_SYSTEM',PK_PickList=5019, DisplayValue='Financial System ', PK_PicklistType=400, SortOrder=20)
,(UsageCode='FINGERPRINT_DAT',PK_PickList=5020, DisplayValue='Fingerprint Database', PK_PicklistType=400, SortOrder=21)
,(UsageCode='GENER_SUPPTEWAY',PK_PickList=5021, DisplayValue='General Support System (GSS) [WAN / Mainframe / Gateway]', PK_PicklistType=400, SortOrder=22)
,(UsageCode='GENER_SYSTPPORT',PK_PickList=5022, DisplayValue='General System and Infrastructure Support', PK_PicklistType=400, SortOrder=23)
,(UsageCode='HUMAN_RESOURC_H',PK_PickList=5023, DisplayValue='Human Resource (HR)', PK_PicklistType=400, SortOrder=24)
,(UsageCode='IDENT_ACCECTORI',PK_PickList=5024, DisplayValue='Identity and Access Management (IDAM) / Identity, Credential, and Access Management (ICAM) / Authentication / Active Directory', PK_PicklistType=400, SortOrder=25)
,(UsageCode='IMMIGR_MOST',PK_PickList=5025, DisplayValue='Immigration (most)', PK_PicklistType=400, SortOrder=26)
,(UsageCode='IMPORTS_EXENTRY',PK_PickList=5026, DisplayValue='Imports-Exports Compliance [Port of Entry]', PK_PicklistType=400, SortOrder=27)
,(UsageCode='INTERNET_BTIONS',PK_PickList=5027, DisplayValue='Internet-Based / Web-Based (Front-Facing Applications)', PK_PicklistType=400, SortOrder=28)
,(UsageCode='IT_SUPPORT_SERV',PK_PickList=5028, DisplayValue='IT support services', PK_PicklistType=400, SortOrder=29)
,(UsageCode='LAW_ENFORC_SERV',PK_PickList=5029, DisplayValue='Law enforcement services', PK_PicklistType=400, SortOrder=30)
,(UsageCode='LOCAL_AREAK_LAN',PK_PickList=5030, DisplayValue='Local Area Network (LAN)', PK_PicklistType=400, SortOrder=31)
,(UsageCode='LOSS_LIFE_POTEN',PK_PickList=5031, DisplayValue='Loss of Life Potential ', PK_PicklistType=400, SortOrder=32)
,(UsageCode='MANAG_MEDI_DATA',PK_PickList=5032, DisplayValue='Manage medical related data', PK_PicklistType=400, SortOrder=33)
,(UsageCode='OFFIC_INSPR_OIG',PK_PickList=5033, DisplayValue='Office of the Inspector General (OIG)', PK_PicklistType=400, SortOrder=34)
,(UsageCode='OTHER',PK_PickList=5034, DisplayValue='Other', PK_PicklistType=400, SortOrder=35)
,(UsageCode='PAYROL',PK_PickList=5035, DisplayValue='Payroll ', PK_PicklistType=400, SortOrder=36)
,(UsageCode='PHYSIC_ACC_PACS',PK_PickList=5036, DisplayValue='Physical Access Control Systems (PACS)', PK_PicklistType=400, SortOrder=37)
,(UsageCode='PROCUR_SYSTEM',PK_PickList=5037, DisplayValue='Procurement systems', PK_PicklistType=400, SortOrder=38)
,(UsageCode='RADIO_COMMUN',PK_PickList=5038, DisplayValue='Radio communications', PK_PicklistType=400, SortOrder=39)
,(UsageCode='REAL_TIM_DUPDAT',PK_PickList=5039, DisplayValue='Real-time data alerts and updates', PK_PicklistType=400, SortOrder=40)
,(UsageCode='REAL_TIM_IMAGER',PK_PickList=5040, DisplayValue='Real-time imagery', PK_PicklistType=400, SortOrder=41)
,(UsageCode='SECUR_CLEATIONS',PK_PickList=5041, DisplayValue='Security Clearance / Background Investigations ', PK_PicklistType=400, SortOrder=42)
,(UsageCode='SECUR_OPERR_SOC',PK_PickList=5042, DisplayValue='Security Operations Center (SOC)', PK_PicklistType=400, SortOrder=43)
,(UsageCode='SUPERVISORYSTEM',PK_PickList=5043, DisplayValue='Supervisory Control and Data Acquisition (SCADA) – electrical systems', PK_PicklistType=400, SortOrder=44)
,(UsageCode='SUPPORT_VUSSESS',PK_PickList=5044, DisplayValue='Support to Vulnerability  Assessments', PK_PicklistType=400, SortOrder=45)
,(UsageCode='TACTIC_COMMUN',PK_PickList=5045, DisplayValue='Tactical communications', PK_PicklistType=400, SortOrder=46)
,(UsageCode='TRUST_INTET_TIC',PK_PickList=5046, DisplayValue='Trusted Internet Connection (TIC)', PK_PicklistType=400, SortOrder=47)
,(UsageCode='WEATHER_WAERVIC',PK_PickList=5047, DisplayValue='Weather warning and analysis services', PK_PicklistType=400, SortOrder=48)
,(UsageCode='WEB_BASE_MYSTEM',PK_PickList=5048, DisplayValue='Web based monitoring system', PK_PicklistType=400, SortOrder=49)
,(UsageCode='OTHER',PK_PickList=5049, DisplayValue='Other ', PK_PicklistType=400, SortOrder=50)
,(UsageCode='CYBER_SECUR_SUP',PK_PickList=5059, DisplayValue='Cyber Security Support', PK_PicklistType=401, SortOrder=1)
,(UsageCode='FINANCI_INPPORT',PK_PickList=5060, DisplayValue='Financial Information Support', PK_PicklistType=401, SortOrder=2)
,(UsageCode='MEDICAL_HEPPORT',PK_PickList=5061, DisplayValue='Medical/health care Support', PK_PicklistType=401, SortOrder=3)
,(UsageCode='DATA_STORAG_MAN',PK_PickList=5062, DisplayValue='Data storage and management', PK_PicklistType=401, SortOrder=4)
,(UsageCode='LEGAL_SERVIC',PK_PickList=5063, DisplayValue='Legal Services', PK_PicklistType=401, SortOrder=5)
,(UsageCode='LAW_ENFORC_SERV',PK_PickList=5064, DisplayValue='Law enforcement services', PK_PicklistType=401, SortOrder=6)
,(UsageCode='VETERAN_SUERVIC',PK_PickList=5065, DisplayValue='Veteran support services', PK_PicklistType=401, SortOrder=7)
,(UsageCode='IMMIGR_SERVIC',PK_PickList=5066, DisplayValue='Immigration services', PK_PicklistType=401, SortOrder=8)
,(UsageCode='DATA_ACCESS_SHA',PK_PickList=5067, DisplayValue='Data Access and Sharing', PK_PicklistType=401, SortOrder=9)
,(UsageCode='NASA_SPACE_SERV',PK_PickList=5068, DisplayValue='NASA and space services', PK_PicklistType=401, SortOrder=10)
,(UsageCode='ACCESS_CONTROL',PK_PickList=5069, DisplayValue='Access control', PK_PicklistType=401, SortOrder=11)
,(UsageCode='VISITOR_MANAG',PK_PickList=5070, DisplayValue='Visitor management', PK_PicklistType=401, SortOrder=12)
,(UsageCode='VIDEO_SURVEIL',PK_PickList=5071, DisplayValue='Video surveillance', PK_PicklistType=401, SortOrder=13)
,(UsageCode='PII_DATA_CONTRO',PK_PickList=5072, DisplayValue='PII data control', PK_PicklistType=401, SortOrder=14)
,(UsageCode='COMMUN',PK_PickList=5073, DisplayValue='Communication', PK_PicklistType=401, SortOrder=15)
,(UsageCode='EMERG_DISPATCH',PK_PickList=5074, DisplayValue='Emergency dispatch', PK_PicklistType=401, SortOrder=16)
,(UsageCode='IT_SUPPORT_SERV',PK_PickList=5075, DisplayValue='IT Support service', PK_PicklistType=401, SortOrder=17)
,(UsageCode='DATA_CENTER_WAR',PK_PickList=5076, DisplayValue='Data center/warehouse', PK_PicklistType=401, SortOrder=18)
,(UsageCode='EMERG_ALERT',PK_PickList=5077, DisplayValue='Emergency Alerts', PK_PicklistType=401, SortOrder=19)
,(UsageCode='REAL_TIME_CCESS',PK_PickList=5078, DisplayValue='Real Time data access', PK_PicklistType=401, SortOrder=20)
,(UsageCode='PHYSIC_SECUR',PK_PickList=5079, DisplayValue='Physical Security', PK_PicklistType=401, SortOrder=21)
,(UsageCode='WEATHER_DIALERT',PK_PickList=5080, DisplayValue='Weather Display and alerts', PK_PicklistType=401, SortOrder=22)
,(UsageCode='PAYROL_RELAT_SE',PK_PickList=5081, DisplayValue='Payroll related Services', PK_PicklistType=401, SortOrder=23)
,(UsageCode='WEB_BASE_MONITO',PK_PickList=5082, DisplayValue='Web Based Monitoring', PK_PicklistType=401, SortOrder=24)
,(UsageCode='PROVID_INFERVIC',PK_PickList=5083, DisplayValue='Provides infrastructure services', PK_PicklistType=401, SortOrder=25)
,(UsageCode='OTHER_FREE_TEXT',PK_PickList=5084, DisplayValue='Other [Free Text]', PK_PicklistType=401, SortOrder=26)
,(UsageCode='FEDER_AGENC_EMP',PK_PickList=5094, DisplayValue='Federal Agencies employees', PK_PicklistType=402, SortOrder=1)
,(UsageCode='EMERG_RESPMANAG',PK_PickList=5095, DisplayValue='Emergency responders/emergency managers', PK_PicklistType=402, SortOrder=2)
,(UsageCode='LOCAL_STATONNEL',PK_PickList=5096, DisplayValue='Local, State and Government personnel', PK_PicklistType=402, SortOrder=3)
,(UsageCode='FEDER_EMPLACTOR',PK_PickList=5097, DisplayValue='Federal Employees and designated contractors', PK_PicklistType=402, SortOrder=4)
,(UsageCode='MEMBER_GENER_PU',PK_PickList=5098, DisplayValue='Members of the general public', PK_PicklistType=402, SortOrder=5)
,(UsageCode='NASA_MISSIOYEES',PK_PickList=5099, DisplayValue='NASA (Missions, Services and/or employees)', PK_PicklistType=402, SortOrder=6)
,(UsageCode='FEDERAL_LONFORC',PK_PickList=5100, DisplayValue='Federal, Local, State Law Enforcement', PK_PicklistType=402, SortOrder=7)
,(UsageCode='INTERN_USDA_AGE',PK_PickList=5101, DisplayValue='Internal USDA Agencies', PK_PicklistType=402, SortOrder=8)
,(UsageCode='VA_PERSONNEMBER',PK_PickList=5102, DisplayValue='VA Personnel, VA Contractors, Veterans, Veterans' family members', PK_PicklistType=402, SortOrder=9)
,(UsageCode='NOAA_EMPLOACTOR',PK_PickList=5103, DisplayValue='NOAA employees and contractors', PK_PicklistType=402, SortOrder=10)
,(UsageCode='AVIAT_WORKER',PK_PickList=5104, DisplayValue='Aviation workers', PK_PicklistType=402, SortOrder=11)
,(UsageCode='FEDER_CREDONNEL',PK_PickList=5105, DisplayValue='Federal Credit Unions and other Federal finical personnel', PK_PicklistType=402, SortOrder=12)
,(UsageCode='INTERN_EXTEHOLD',PK_PickList=5106, DisplayValue='Internal and External Stakeholders', PK_PicklistType=402, SortOrder=13)
,(UsageCode='POTENTI_FEPLOYE',PK_PickList=5107, DisplayValue='Potential federal employees', PK_PicklistType=402, SortOrder=14)
,(UsageCode='PUBLIC_OFFICI',PK_PickList=5108, DisplayValue='Public officials', PK_PicklistType=402, SortOrder=15)
,(UsageCode='BORDER_PATROL',PK_PickList=5109, DisplayValue='Border Patrol', PK_PicklistType=402, SortOrder=16)
,(UsageCode='ECONOM_ANALYST',PK_PickList=5110, DisplayValue='Economic Analysts', PK_PicklistType=402, SortOrder=17)
,(UsageCode='INFRASTRUCONNEL',PK_PickList=5111, DisplayValue='Infrastructure Support Personnel', PK_PicklistType=402, SortOrder=18)
,(UsageCode='SLTT_ORGAN',PK_PickList=5112, DisplayValue='SLTT Organizations', PK_PicklistType=402, SortOrder=19)
,(UsageCode='FEDERAL_STOMMUN',PK_PickList=5113, DisplayValue='Federal, State, Local, Tribal, and Territorial communities', PK_PicklistType=402, SortOrder=20)
,(UsageCode='MEDIC_HEALONNEL',PK_PickList=5114, DisplayValue='Medical and Healthcare Personnel', PK_PicklistType=402, SortOrder=21)
,(UsageCode='VISA_APPLIC',PK_PickList=5115, DisplayValue='Visa applicants', PK_PicklistType=402, SortOrder=22)
,(UsageCode='MILITARI_DONNEL',PK_PickList=5116, DisplayValue='Military and Defense Personnel', PK_PicklistType=402, SortOrder=23)
,(UsageCode='GOVERN_SYSTEM',PK_PickList=5117, DisplayValue='other Government systems', PK_PicklistType=402, SortOrder=24)
,(UsageCode='PUBLIC_SYSTEM',PK_PickList=5118, DisplayValue='other public systems', PK_PicklistType=402, SortOrder=25)
,(UsageCode='INTERN_AGENC_US',PK_PickList=5119, DisplayValue='Internal agency users', PK_PicklistType=402, SortOrder=26)
,(UsageCode='EXTERN_AGENC_US',PK_PickList=5120, DisplayValue='External agency users', PK_PicklistType=402, SortOrder=27)
,(UsageCode='OTHER_FREE_TEXT',PK_PickList=5121, DisplayValue='Other [Free Text]', PK_PicklistType=402, SortOrder=28)
,(UsageCode='NONE',PK_PickList=5122, DisplayValue='None', PK_PicklistType=402, SortOrder=29)
,(UsageCode='N_5_YEAR',PK_PickList=5123, DisplayValue='< 5 years', PK_PicklistType=402, SortOrder=30)
,(UsageCode='N_6_10_YEAR',PK_PickList=5124, DisplayValue='> 6 – 10 years', PK_PicklistType=402, SortOrder=31)
,(UsageCode='N_10_15_YEAR',PK_PickList=5125, DisplayValue=' > 10 – 15 years', PK_PicklistType=402, SortOrder=32)
,(UsageCode='N_15_20_YEAR',PK_PickList=5126, DisplayValue=' > 15 – 20 years', PK_PicklistType=402, SortOrder=33)
,(UsageCode='N_20_30_YEAR',PK_PickList=5127, DisplayValue=' > 20 – 30 years', PK_PicklistType=402, SortOrder=34)
,(UsageCode='N_30_40_YEAR',PK_PickList=5128, DisplayValue=' > 30 – 40 years', PK_PicklistType=402, SortOrder=35)
,(UsageCode='N_40_YEAR',PK_PickList=5129, DisplayValue='> 40 years', PK_PicklistType=402, SortOrder=36)
,(UsageCode='N_1_YE',PK_PickList=5139, DisplayValue=' Yes', PK_PicklistType=403, SortOrder=1)
,(UsageCode='N_2_NO',PK_PickList=5140, DisplayValue=' No', PK_PicklistType=403, SortOrder=2)
,(UsageCode='N_3_UNKNOWN',PK_PickList=5141, DisplayValue=' Unknown', PK_PicklistType=403, SortOrder=3)
,(UsageCode='LEGACI_CODMUMPS',PK_PickList=5151, DisplayValue='Legacy codebase (COBOL, MUMPS)', PK_PicklistType=404, SortOrder=1)
,(UsageCode='LACK_POOR_DOCUM',PK_PickList=5152, DisplayValue='Lack of or poor documentation', PK_PicklistType=404, SortOrder=2)
,(UsageCode='LEGACI_INFRASTR',PK_PickList=5153, DisplayValue='Legacy infrastructure', PK_PicklistType=404, SortOrder=3)
,(UsageCode='AD_HOC_INFRASTR',PK_PickList=5154, DisplayValue='Ad-hoc infrastructure ', PK_PicklistType=404, SortOrder=4)
,(UsageCode='HARDWAR_SOPPORT',PK_PickList=5155, DisplayValue='Hardware or software with no vendor/manufacturer support', PK_PicklistType=404, SortOrder=5)
,(UsageCode='OUTDAT_INANTORI',PK_PickList=5156, DisplayValue='Outdated or inaccurate inventory', PK_PicklistType=404, SortOrder=6)
,(UsageCode='LIMIT_FUNCTION',PK_PickList=5157, DisplayValue='Limited Functionality', PK_PicklistType=404, SortOrder=7)
,(UsageCode='OTHER_FREE_TEXT',PK_PickList=5158, DisplayValue='Other [Free Text]', PK_PicklistType=404, SortOrder=8)
,(UsageCode='N_1_YE',PK_PickList=5168, DisplayValue=' Yes', PK_PicklistType=405, SortOrder=1)
,(UsageCode='N_2_NO',PK_PickList=5169, DisplayValue=' No', PK_PicklistType=405, SortOrder=2)
,(UsageCode='N_3_UNKNOWN',PK_PickList=5170, DisplayValue=' Unknown', PK_PicklistType=405, SortOrder=3)
,(UsageCode='N_1_YE',PK_PickList=5180, DisplayValue=' Yes', PK_PicklistType=406, SortOrder=1)
,(UsageCode='N_2_NO',PK_PickList=5181, DisplayValue=' No', PK_PicklistType=406, SortOrder=2)
,(UsageCode='N_3_UNKNOWN',PK_PickList=5182, DisplayValue=' Unknown', PK_PicklistType=406, SortOrder=3)
,(UsageCode='N_1_YE',PK_PickList=5192, DisplayValue=' Yes', PK_PicklistType=407, SortOrder=1)
,(UsageCode='N_2_NO',PK_PickList=5193, DisplayValue=' No', PK_PicklistType=407, SortOrder=2)
,(UsageCode='N_3_UNKNOWN',PK_PickList=5194, DisplayValue=' Unknown', PK_PicklistType=407, SortOrder=3)
,(UsageCode='DATE_MM_YYYY',PK_PickList=5204, DisplayValue='DATE (MM/YYYY)', PK_PicklistType=408, SortOrder=1)
,(UsageCode='N_1_YE',PK_PickList=5214, DisplayValue=' Yes', PK_PicklistType=409, SortOrder=1)
,(UsageCode='N_2_NO',PK_PickList=5215, DisplayValue=' No', PK_PicklistType=409, SortOrder=2)
,(UsageCode='N_3_UNKNOWN',PK_PickList=5216, DisplayValue=' Unknown', PK_PicklistType=409, SortOrder=3)
,(UsageCode='N_1_FREE_TEXT',PK_PickList=5226, DisplayValue=' Free text', PK_PicklistType=410, SortOrder=1)
,(UsageCode='N_1_YE',PK_PickList=5236, DisplayValue=' Yes', PK_PicklistType=411, SortOrder=1)
,(UsageCode='N_2_NO',PK_PickList=5237, DisplayValue=' No', PK_PicklistType=411, SortOrder=2)
,(UsageCode='N_3_UNKNOWN',PK_PickList=5238, DisplayValue=' Unknown', PK_PicklistType=411, SortOrder=3)
,(UsageCode='N_1_YE',PK_PickList=5248, DisplayValue=' Yes', PK_PicklistType=412, SortOrder=1)
,(UsageCode='N_2_NO',PK_PickList=5249, DisplayValue=' No', PK_PicklistType=412, SortOrder=2)
,(UsageCode='N_3_UNKNOWN',PK_PickList=5250, DisplayValue=' Unknown', PK_PicklistType=412, SortOrder=3)
,(UsageCode='N_1_CLOUD',PK_PickList=5260, DisplayValue=' Cloud', PK_PicklistType=413, SortOrder=1)
,(UsageCode='N_2_MAINFRAM',PK_PickList=5261, DisplayValue=' Mainframe', PK_PicklistType=413, SortOrder=2)
,(UsageCode='N_3_GSS',PK_PickList=5262, DisplayValue=' GSS', PK_PicklistType=413, SortOrder=3)
,(UsageCode='N_4_WEB_APPLIC',PK_PickList=5263, DisplayValue=' Web Application', PK_PicklistType=413, SortOrder=4)
,(UsageCode='N_5_APPLIC_PLAT',PK_PickList=5264, DisplayValue=' Application Platform', PK_PicklistType=413, SortOrder=5)
,(UsageCode='N_6_ICS_SCADA',PK_PickList=5265, DisplayValue=' ICS/SCADA', PK_PicklistType=413, SortOrder=6)
,(UsageCode='N_7_CLIENT_SERV',PK_PickList=5266, DisplayValue=' Client/Server', PK_PicklistType=413, SortOrder=7)
,(UsageCode='N_8_OTHER_FREE_',PK_PickList=5267, DisplayValue=' Other [Free Text]', PK_PicklistType=413, SortOrder=8)
,(UsageCode='N_1_PAA',PK_PickList=5277, DisplayValue=' Paas', PK_PicklistType=414, SortOrder=1)
,(UsageCode='N_2_SAA',PK_PickList=5278, DisplayValue=' SaaS', PK_PicklistType=414, SortOrder=2)
,(UsageCode='N_3_IAA',PK_PickList=5279, DisplayValue=' IaaS', PK_PicklistType=414, SortOrder=3)
,(UsageCode='N_4_HYBRID',PK_PickList=5280, DisplayValue=' Hybrid', PK_PicklistType=414, SortOrder=4)
,(UsageCode='N_5_OTHER_FREE_',PK_PickList=5281, DisplayValue=' Other [Free Text]', PK_PicklistType=414, SortOrder=5)
,(UsageCode='N_1_YE',PK_PickList=5291, DisplayValue=' Yes', PK_PicklistType=415, SortOrder=1)
,(UsageCode='N_2_NO',PK_PickList=5292, DisplayValue=' No', PK_PicklistType=415, SortOrder=2)
,(UsageCode='N_3_UNKNOWN',PK_PickList=5293, DisplayValue=' Unknown', PK_PicklistType=415, SortOrder=3)
,(UsageCode='N_1_FREE_TEXT',PK_PickList=5303, DisplayValue=' Free Text', PK_PicklistType=416, SortOrder=1)
,(UsageCode='N_1_GSS',PK_PickList=5313, DisplayValue=' GSS', PK_PicklistType=417, SortOrder=1)
,(UsageCode='N_2_WEB_APPLIC',PK_PickList=5314, DisplayValue=' Web Application', PK_PicklistType=417, SortOrder=2)
,(UsageCode='N_3_BOTH',PK_PickList=5315, DisplayValue=' Both', PK_PicklistType=417, SortOrder=3)
,(UsageCode='N_4_UNKNOWN',PK_PickList=5316, DisplayValue=' Unknown', PK_PicklistType=417, SortOrder=4)
,(UsageCode='N_5_NEITHER',PK_PickList=5317, DisplayValue=' Neither', PK_PicklistType=417, SortOrder=5)
,(UsageCode='N_1_WEB_BR_TEXT',PK_PickList=5327, DisplayValue=' Web Browser: Free Text', PK_PicklistType=418, SortOrder=1)
,(UsageCode='N_2_WEB_AP_TEXT',PK_PickList=5328, DisplayValue=' Web Application Server: Free Text', PK_PicklistType=418, SortOrder=2)
,(UsageCode='N_3_DATABA_TEXT',PK_PickList=5329, DisplayValue=' Database: Free Text', PK_PicklistType=418, SortOrder=3)
,(UsageCode='N_4_UNKNOWN',PK_PickList=5330, DisplayValue=' Unknown', PK_PicklistType=418, SortOrder=4)
,(UsageCode='HTML',PK_PickList=5340, DisplayValue='HTML', PK_PicklistType=419, SortOrder=1)
,(UsageCode='CSS',PK_PickList=5341, DisplayValue='CSS', PK_PicklistType=419, SortOrder=2)
,(UsageCode='JS',PK_PickList=5342, DisplayValue='JS', PK_PicklistType=419, SortOrder=3)
,(UsageCode='PHP',PK_PickList=5343, DisplayValue='PHP', PK_PicklistType=419, SortOrder=4)
,(UsageCode='JAVA',PK_PickList=5344, DisplayValue='Java', PK_PicklistType=419, SortOrder=5)
,(UsageCode='RUBI_RAIL',PK_PickList=5345, DisplayValue='Ruby on Rails', PK_PicklistType=419, SortOrder=6)
,(UsageCode='SMYFONI_ANACT_J',PK_PickList=5346, DisplayValue='Smyfony Angular JS React.js', PK_PicklistType=419, SortOrder=7)
,(UsageCode='CAKE_PHP',PK_PickList=5347, DisplayValue='Cake PHP', PK_PicklistType=419, SortOrder=8)
,(UsageCode='ASP_NET',PK_PickList=5348, DisplayValue='Asp.net', PK_PicklistType=419, SortOrder=9)
,(UsageCode='NODE_J',PK_PickList=5349, DisplayValue='Node.js', PK_PicklistType=419, SortOrder=10)
,(UsageCode='METEOR',PK_PickList=5350, DisplayValue='Meteor', PK_PicklistType=419, SortOrder=11)
,(UsageCode='LARAVEL',PK_PickList=5351, DisplayValue='Laravel', PK_PicklistType=419, SortOrder=12)
,(UsageCode='EMBER',PK_PickList=5352, DisplayValue='Ember', PK_PicklistType=419, SortOrder=13)
,(UsageCode='DJANGO',PK_PickList=5353, DisplayValue='Django', PK_PicklistType=419, SortOrder=14)
,(UsageCode='EXPRESS',PK_PickList=5354, DisplayValue='Express', PK_PicklistType=419, SortOrder=15)
,(UsageCode='SPRING',PK_PickList=5355, DisplayValue='Spring', PK_PicklistType=419, SortOrder=16)
,(UsageCode='FLASK',PK_PickList=5356, DisplayValue='Flask', PK_PicklistType=419, SortOrder=17)
,(UsageCode='DRUPAL',PK_PickList=5357, DisplayValue='Drupal', PK_PicklistType=419, SortOrder=18)
,(UsageCode='WORDPRESS',PK_PickList=5358, DisplayValue='WordPress', PK_PicklistType=419, SortOrder=19)
,(UsageCode='BOOTSTRAP',PK_PickList=5359, DisplayValue='Bootstrap', PK_PicklistType=419, SortOrder=20)
,(UsageCode='WEB2PI',PK_PickList=5360, DisplayValue='web2py', PK_PicklistType=419, SortOrder=21)
,(UsageCode='TURBOGEAR',PK_PickList=5361, DisplayValue='TurboGears', PK_PicklistType=419, SortOrder=22)
,(UsageCode='SINATRA',PK_PickList=5362, DisplayValue='Sinatra', PK_PicklistType=419, SortOrder=23)
,(UsageCode='ZEND_FRAMEWORK',PK_PickList=5363, DisplayValue='Zend Framework', PK_PicklistType=419, SortOrder=24)
,(UsageCode='NOT_LISTED_OTH',PK_PickList=5364, DisplayValue='Not Listed/Other', PK_PicklistType=419, SortOrder=25)
,(UsageCode='MICROSOFT_WINDO',PK_PickList=5374, DisplayValue='Microsoft Windows, ', PK_PicklistType=420, SortOrder=1)
,(UsageCode='APPL_MACOS',PK_PickList=5375, DisplayValue='Apple MacOS, ', PK_PicklistType=420, SortOrder=2)
,(UsageCode='IOS',PK_PickList=5376, DisplayValue='iOS, ', PK_PicklistType=420, SortOrder=3)
,(UsageCode='UBUNTU',PK_PickList=5377, DisplayValue='Ubuntu, ', PK_PicklistType=420, SortOrder=4)
,(UsageCode='CENTOS',PK_PickList=5378, DisplayValue='CentOS, ', PK_PicklistType=420, SortOrder=5)
,(UsageCode='UNIX',PK_PickList=5379, DisplayValue='Unix, ', PK_PicklistType=420, SortOrder=6)
,(UsageCode='ANDROID',PK_PickList=5380, DisplayValue='Android, ', PK_PicklistType=420, SortOrder=7)
,(UsageCode='WINDOW_10_WIN10',PK_PickList=5381, DisplayValue='Windows 10(and EOS Win10), ', PK_PicklistType=420, SortOrder=8)
,(UsageCode='MS_DOS_WINERNEL',PK_PickList=5382, DisplayValue='MS-DOS, Windows Vista, Linux Kernel, ', PK_PicklistType=420, SortOrder=9)
,(UsageCode='HYPERVISORE_ETC',PK_PickList=5383, DisplayValue='HyperVisor (such as VMware), etc.', PK_PicklistType=420, SortOrder=10)
,(UsageCode='OTHER_FREE_TEXT',PK_PickList=5384, DisplayValue='Other (Free Text)', PK_PicklistType=420, SortOrder=11)
,(UsageCode='N_1_YE',PK_PickList=5394, DisplayValue=' Yes', PK_PicklistType=421, SortOrder=1)
,(UsageCode='N_2_NO',PK_PickList=5395, DisplayValue=' No', PK_PicklistType=421, SortOrder=2)
,(UsageCode='N_3_UNKNOWN',PK_PickList=5396, DisplayValue=' Unknown', PK_PicklistType=421, SortOrder=3)
,(UsageCode='N_1_YE',PK_PickList=5406, DisplayValue=' Yes', PK_PicklistType=422, SortOrder=1)
,(UsageCode='N_2_NO',PK_PickList=5407, DisplayValue=' No', PK_PicklistType=422, SortOrder=2)
,(UsageCode='N_3_UNKNOWN',PK_PickList=5408, DisplayValue=' Unknown', PK_PicklistType=422, SortOrder=3)
,(UsageCode='N_1_YE',PK_PickList=5418, DisplayValue=' Yes', PK_PicklistType=423, SortOrder=1)
,(UsageCode='N_2_NO',PK_PickList=5419, DisplayValue=' No', PK_PicklistType=423, SortOrder=2)
,(UsageCode='N_3_UNKNOWN',PK_PickList=5420, DisplayValue=' Unknown', PK_PicklistType=423, SortOrder=3)
,(UsageCode='N_1_UPSTREAM',PK_PickList=5430, DisplayValue=' Upstream', PK_PicklistType=424, SortOrder=1)
,(UsageCode='N_2_DOWNSTREAM',PK_PickList=5431, DisplayValue=' Downstream', PK_PicklistType=424, SortOrder=2)
,(UsageCode='N_3_BOTH',PK_PickList=5432, DisplayValue=' Both', PK_PicklistType=424, SortOrder=3)
,(UsageCode='N_1_FREE_TEXT',PK_PickList=5442, DisplayValue=' Free text', PK_PicklistType=425, SortOrder=1)
,(UsageCode='N_1_FREE_TEXT',PK_PickList=5452, DisplayValue=' Free text', PK_PicklistType=426, SortOrder=1)
,(UsageCode='N_1_GOVERN_GOGO',PK_PickList=5462, DisplayValue=' Government Owned – Government Operated (GoGo)', PK_PicklistType=427, SortOrder=1)
,(UsageCode='N_2_GOVERN_GOCO',PK_PickList=5463, DisplayValue=' Government Owned – Contractor Operated (GoCo)', PK_PicklistType=427, SortOrder=2)
,(UsageCode='N_3_CONTRA_COCO',PK_PickList=5464, DisplayValue=' Contractor Owned – Contractor Operated, (CoCo)', PK_PicklistType=427, SortOrder=3)
,(UsageCode='N_4_FEDER_FFRDC',PK_PickList=5465, DisplayValue=' Federally Funded Research and Development Center (FFRDC)', PK_PicklistType=427, SortOrder=4)
,(UsageCode='N_5_OTHER_FREE_',PK_PickList=5466, DisplayValue=' Other (Free Text)', PK_PicklistType=427, SortOrder=5)
,(UsageCode='N_1_FREE_TEXT',PK_PickList=5476, DisplayValue=' Free text', PK_PicklistType=428, SortOrder=1)
,(UsageCode='N_1_FREE_TEXT',PK_PickList=5486, DisplayValue=' Free text', PK_PicklistType=429, SortOrder=1)
,(UsageCode='N_1_YE',PK_PickList=5496, DisplayValue=' Yes', PK_PicklistType=430, SortOrder=1)
,(UsageCode='N_2_NO',PK_PickList=5497, DisplayValue=' No', PK_PicklistType=430, SortOrder=2)
,(UsageCode='N_3_UNKNOWN',PK_PickList=5498, DisplayValue=' Unknown', PK_PicklistType=430, SortOrder=3)
,(UsageCode='N_1_FREE_TEXT',PK_PickList=5508, DisplayValue=' Free text', PK_PicklistType=431, SortOrder=1)
,(UsageCode='N_1_FEDER_EMPLO',PK_PickList=5518, DisplayValue=' Federal Employees', PK_PicklistType=432, SortOrder=1)
,(UsageCode='N_2_FEDER_ACTOR',PK_PickList=5519, DisplayValue=' Federal employees and direct support contractors', PK_PicklistType=432, SortOrder=2)
,(UsageCode='N_3_CONTRACTOR',PK_PickList=5520, DisplayValue=' Contractors', PK_PicklistType=432, SortOrder=3)
,(UsageCode='N_1_ENCRYPKNOWN',PK_PickList=5530, DisplayValue=' Encryption of data at rest
2. Encryption of data in transit
3. Least privilege principles
4. Application Allowlisting (whitelisting)
5. Other (Free Text)
6. Unknown', PK_PicklistType=433, SortOrder=1)
,(UsageCode='N_1_SECUR_MANAG',PK_PickList=5540, DisplayValue=' Security Operations Center (SOC) as a Service such as Asset Management', PK_PicklistType=434, SortOrder=1)
,(UsageCode='N_2_AWAR_TRAIN',PK_PickList=5541, DisplayValue=' Awareness and Training', PK_PicklistType=434, SortOrder=2)
,(UsageCode='N_3_DETECT_PROC',PK_PickList=5542, DisplayValue=' Detection Processes', PK_PicklistType=434, SortOrder=3)
,(UsageCode='N_4_GOVERNDURES',PK_PickList=5543, DisplayValue=' Governance: Information Protection Processes and Procedures;', PK_PicklistType=434, SortOrder=4)
,(UsageCode='N_5_PROTECNOLOG',PK_PickList=5544, DisplayValue=' Protective Technology', PK_PicklistType=434, SortOrder=5)
,(UsageCode='N_6_RISK_ASSESS',PK_PickList=5545, DisplayValue=' Risk Assessment', PK_PicklistType=434, SortOrder=6)
,(UsageCode='N_7_SECUR_NITOR',PK_PickList=5546, DisplayValue=' Security Continuous Monitoring', PK_PicklistType=434, SortOrder=7)
,(UsageCode='N_8_SUPPLIMANAG',PK_PickList=5547, DisplayValue=' Supply Chain Risk Management', PK_PicklistType=434, SortOrder=8)
,(UsageCode='N_1_CONTING_CDM',PK_PickList=5557, DisplayValue=' Continuous Diagnostics and Mitigation (CDM)', PK_PicklistType=435, SortOrder=1)
,(UsageCode='N_2_PROTECT_DN_',PK_PickList=5558, DisplayValue=' Protective DNS (pDNS)', PK_PicklistType=435, SortOrder=2)
,(UsageCode='N_3_VULNERM_VDP',PK_PickList=5559, DisplayValue=' Vulnerability Disclosure Program (VDP)', PK_PicklistType=435, SortOrder=3)
,(UsageCode='N_4_OTHER_FREE_',PK_PickList=5560, DisplayValue=' Other (Free Text)', PK_PicklistType=435, SortOrder=4)
,(UsageCode='N_5_UNKNOWN',PK_PickList=5561, DisplayValue=' Unknown', PK_PicklistType=435, SortOrder=5)
,(UsageCode='N_6_NO',PK_PickList=5562, DisplayValue=' No', PK_PicklistType=435, SortOrder=6)
,(UsageCode='N_1_YE',PK_PickList=5572, DisplayValue=' Yes', PK_PicklistType=436, SortOrder=1)
,(UsageCode='N_2_NO',PK_PickList=5573, DisplayValue=' No', PK_PicklistType=436, SortOrder=2)
,(UsageCode='N_3_UNKNOWN',PK_PickList=5574, DisplayValue=' Unknown', PK_PicklistType=436, SortOrder=3)
,(UsageCode='N_1_YE',PK_PickList=5584, DisplayValue=' Yes', PK_PicklistType=437, SortOrder=1)
,(UsageCode='N_2_NO',PK_PickList=5585, DisplayValue=' No', PK_PicklistType=437, SortOrder=2)
,(UsageCode='N_3_UNKNOWN',PK_PickList=5586, DisplayValue=' Unknown', PK_PicklistType=437, SortOrder=3)
,(UsageCode='N_1_YE',PK_PickList=5596, DisplayValue=' Yes', PK_PicklistType=438, SortOrder=1)
,(UsageCode='N_2_NO',PK_PickList=5597, DisplayValue=' No', PK_PicklistType=438, SortOrder=2)
,(UsageCode='N_3_UNKNOWN',PK_PickList=5598, DisplayValue=' Unknown', PK_PicklistType=438, SortOrder=3)
,(UsageCode='N_1_FREE_TEXT',PK_PickList=5608, DisplayValue=' Free Text', PK_PicklistType=439, SortOrder=1)
,(UsageCode='N_1_YE',PK_PickList=5618, DisplayValue=' Yes', PK_PicklistType=440, SortOrder=1)
,(UsageCode='N_2_NO',PK_PickList=5619, DisplayValue=' No', PK_PicklistType=440, SortOrder=2)
,(UsageCode='N_3_UNKNOWN',PK_PickList=5620, DisplayValue=' Unknown', PK_PicklistType=440, SortOrder=3)
,(UsageCode='N_1_FREE_TEXT',PK_PickList=5630, DisplayValue=' Free Text', PK_PicklistType=441, SortOrder=1)
,(UsageCode='N_1_RESULTAVAIL',PK_PickList=5640, DisplayValue=' Resulted in unscheduled downtime/unavailability', PK_PicklistType=442, SortOrder=1)
,(UsageCode='N_2_REQUIRMONTH',PK_PickList=5641, DisplayValue=' Required outside incident response support  in the last 12 months', PK_PicklistType=442, SortOrder=2)
,(UsageCode='N_1_INTEG',PK_PickList=5651, DisplayValue=' Integer', PK_PicklistType=443, SortOrder=1)
,(UsageCode='N_1_INTEG',PK_PickList=5661, DisplayValue=' Integer', PK_PicklistType=444, SortOrder=1)
,(UsageCode='N_1_YE',PK_PickList=5671, DisplayValue=' Yes', PK_PicklistType=445, SortOrder=1)
,(UsageCode='N_2_NO',PK_PickList=5672, DisplayValue=' No', PK_PicklistType=445, SortOrder=2)
,(UsageCode='N_3_UNKNOWN',PK_PickList=5673, DisplayValue=' Unknown', PK_PicklistType=445, SortOrder=3)
,(UsageCode='N_1_FREE_TEXT',PK_PickList=5683, DisplayValue=' Free Text', PK_PicklistType=446, SortOrder=1)
,(UsageCode='DOJ_1_ADVIRESID',PK_PickList=5693, DisplayValue='DOJ(1) - Advise and Represent the President', PK_PicklistType=447, SortOrder=1)
,(UsageCode='DOJ_2_PROTCOURT',PK_PickList=5694, DisplayValue='DOJ(2) - Protect Senior Officials and the Courts', PK_PicklistType=447, SortOrder=2)
,(UsageCode='DOJ_3_PERFEVIEW',PK_PickList=5695, DisplayValue='DOJ(3) - Perform Critical Legal Reviews', PK_PicklistType=447, SortOrder=3)
,(UsageCode='DOJ_4_FIGHIONAG',PK_PickList=5696, DisplayValue='DOJ(4) - Fight Terrorism and Espionage', PK_PicklistType=447, SortOrder=4)
,(UsageCode='DOJ_5_CONDACTIV',PK_PickList=5697, DisplayValue='DOJ(5) - Conduct Law Enforcement Activities', PK_PicklistType=447, SortOrder=5)
,(UsageCode='DOJ_6_OPERRISON',PK_PickList=5698, DisplayValue='DOJ(6) - Operate Federal Prisons', PK_PicklistType=447, SortOrder=6)
,(UsageCode='DHS_1_SECUORDER',PK_PickList=5699, DisplayValue='DHS(1) - Secure and Manage the Borders', PK_PicklistType=447, SortOrder=7)
,(UsageCode='DHS_2_SECURSPAC',PK_PickList=5700, DisplayValue='DHS(2) - Secure Critical Infrastructure and Cyberspace', PK_PicklistType=447, SortOrder=8)
,(UsageCode='DHS_3_PROTEADER',PK_PickList=5701, DisplayValue='DHS(3) - Protect National Leaders', PK_PicklistType=447, SortOrder=9)
,(UsageCode='DHS_4_PROV_AWAR',PK_PickList=5702, DisplayValue='DHS(4) - Provide Domestic Situational Awareness', PK_PicklistType=447, SortOrder=10)
,(UsageCode='DHS_5_ENFOREGUL',PK_PickList=5703, DisplayValue='DHS(5) - Enforce Homeland Security Laws and Regulations', PK_PicklistType=447, SortOrder=11)
,(UsageCode='DHS_6_COORSPONS',PK_PickList=5704, DisplayValue='DHS(6) - Coordinate Continuity and Incident Response', PK_PicklistType=447, SortOrder=12)
,(UsageCode='DHS_7_COOROVERI',PK_PickList=5705, DisplayValue='DHS(7) - Coordinate Disaster Recovery', PK_PicklistType=447, SortOrder=13)
,(UsageCode='GSA_1_LEADTITUT',PK_PickList=5706, DisplayValue='GSA(1) - Lead Government Reconstitution', PK_PicklistType=447, SortOrder=14)
,(UsageCode='DOD_1_ADVIOLICI',PK_PickList=5707, DisplayValue='DOD(1) - Advise on National Defense Policy', PK_PicklistType=447, SortOrder=15)
,(UsageCode='DOD_2_DEFESTATE',PK_PickList=5708, DisplayValue='DOD(2) - Defend the Security of the United States', PK_PicklistType=447, SortOrder=16)
,(UsageCode='DOD_3_COLLELLIG',PK_PickList=5709, DisplayValue='DOD(3) - Collect, Analyze, and Disseminate Intelligence', PK_PicklistType=447, SortOrder=17)
,(UsageCode='DOD_4_PROMSECUR',PK_PickList=5710, DisplayValue='DOD(4) - Promote National Security', PK_PicklistType=447, SortOrder=18)
,(UsageCode='DOD_5_CONDSPONS',PK_PickList=5711, DisplayValue='DOD(5) - Conduct Domestic Emergency Response', PK_PicklistType=447, SortOrder=19)
,(UsageCode='DOS_1_FORMOLICI',PK_PickList=5712, DisplayValue='DOS(1) - Formulate Foreign Affairs Policy', PK_PicklistType=447, SortOrder=20)
,(UsageCode='DOS_2_MAINRELAT',PK_PickList=5713, DisplayValue='DOS(2) - Maintain Foreign Diplomatic Relations', PK_PicklistType=447, SortOrder=21)
,(UsageCode='DOS_3_MAIN_AWAR',PK_PickList=5714, DisplayValue='DOS(3) - Maintain International Situational Awareness', PK_PicklistType=447, SortOrder=22)
,(UsageCode='DOS_4_SUPPERSEA',PK_PickList=5715, DisplayValue='DOS(4) - Support U.S.Citizens Overseas', PK_PicklistType=447, SortOrder=23)
,(UsageCode='CIA_1_PRODEPORT',PK_PickList=5716, DisplayValue='CIA(1) - Produce Timely Intelligence Reports', PK_PicklistType=447, SortOrder=24)
,(UsageCode='CIA_2_COLLELLIG',PK_PickList=5717, DisplayValue='CIA(2) - Collect Intelligence ', PK_PicklistType=447, SortOrder=25)
,(UsageCode='CIA_3_COND_OPER',PK_PickList=5718, DisplayValue='CIA(3) - Conduct Covert Operations', PK_PicklistType=447, SortOrder=26)
,(UsageCode='DOI_1_PROV_LAND',PK_PickList=5719, DisplayValue='DOI(1) - Provide Emergency Response on Federal Lands', PK_PicklistType=447, SortOrder=27)
,(UsageCode='DOI_2_PROV_LAND',PK_PickList=5720, DisplayValue='DOI(2) - Provide Law Enforcement on Federal Lands', PK_PicklistType=447, SortOrder=28)
,(UsageCode='DOI_3_PROVSPONS',PK_PickList=5721, DisplayValue='DOI(3) - Provide National Emergency Response', PK_PicklistType=447, SortOrder=29)
,(UsageCode='DOI_4_MAINTRIBE',PK_PickList=5722, DisplayValue='DOI(4) - Maintain Relations with Insular Areas and Tribes', PK_PicklistType=447, SortOrder=30)
,(UsageCode='DOI_5_PROVPOWER',PK_PickList=5723, DisplayValue='DOI(5) - Provide Water and Electric Power', PK_PicklistType=447, SortOrder=31)
,(UsageCode='DOE_1_ENSUAFETI',PK_PickList=5724, DisplayValue='DOE(1) - Ensure Nuclear Materials Safety', PK_PicklistType=447, SortOrder=32)
,(UsageCode='DOE_2_RESPINCID',PK_PickList=5725, DisplayValue='DOE(2) - Respond to Nuclear Incidents', PK_PicklistType=447, SortOrder=33)
,(UsageCode='DOE_3_MANAUCTUR',PK_PickList=5726, DisplayValue='DOE(3) - Manage Energy Infrastructure', PK_PicklistType=447, SortOrder=34)
,(UsageCode='DOC_1_PREVIOLAT',PK_PickList=5727, DisplayValue='DOC(1) - Prevent Export Control Violations', PK_PicklistType=447, SortOrder=35)
,(UsageCode='DOC_2_PROVAGERI',PK_PickList=5728, DisplayValue='DOC(2) - Provide Satellite Imagery', PK_PicklistType=447, SortOrder=36)
,(UsageCode='DOC_3_PROVECAST',PK_PickList=5729, DisplayValue='DOC(3) - Provide Meteorological Forecasts', PK_PicklistType=447, SortOrder=37)
,(UsageCode='DOC_4_MAINOMMUN',PK_PickList=5730, DisplayValue='DOC(4) - Maintain Operational Federal Communications', PK_PicklistType=447, SortOrder=38)
,(UsageCode='TREAS_1_SAYSTEM',PK_PickList=5731, DisplayValue='TREAS(1) - Safeguard the Economy and the Financial System', PK_PicklistType=447, SortOrder=39)
,(UsageCode='TREAS_2_USHREAT',PK_PickList=5732, DisplayValue='TREAS(2) - Use Financial Measures to Counter National Security Threats', PK_PicklistType=447, SortOrder=40)
,(UsageCode='TREAS_3_MAINANC',PK_PickList=5733, DisplayValue='TREAS(3) - Manage Government Finances', PK_PicklistType=447, SortOrder=41)
,(UsageCode='TREAS_4_PRTABIL',PK_PickList=5734, DisplayValue='TREAS(4) - Promote International Financial Stability', PK_PicklistType=447, SortOrder=42)
,(UsageCode='USDA_1_ENSAFETI',PK_PickList=5735, DisplayValue='USDA(1) - Ensure Food Safety', PK_PicklistType=447, SortOrder=43)
,(UsageCode='USDA_2_PROUPPLI',PK_PickList=5736, DisplayValue='USDA(2) - Provide Emergency Food Supplies', PK_PicklistType=447, SortOrder=44)
,(UsageCode='USDA_3_FIG_FIRE',PK_PickList=5737, DisplayValue='USDA(3) - Fight Forest Fires', PK_PicklistType=447, SortOrder=45)
,(UsageCode='USDA_4_PRO_LAND',PK_PickList=5738, DisplayValue='USDA(4) - Provide Safety and Security on Public Lands', PK_PicklistType=447, SortOrder=46)
,(UsageCode='FRS_1_CONDOLICI',PK_PickList=5739, DisplayValue='FRS(1) - Conduct Monetary Policy', PK_PicklistType=447, SortOrder=47)
,(UsageCode='FRS_2_MAINTABIL',PK_PickList=5740, DisplayValue='FRS(2) - Maintain Financial System Stability', PK_PicklistType=447, SortOrder=48)
,(UsageCode='FRS_3_REGUL_BAN',PK_PickList=5741, DisplayValue='FRS(3) - Regulate Banking', PK_PicklistType=447, SortOrder=49)
,(UsageCode='FRS_4_PROVERVIC',PK_PickList=5742, DisplayValue='FRS(4) - Provide Financial Services', PK_PicklistType=447, SortOrder=50)
,(UsageCode='DOT_1_ENSUUCTUR',PK_PickList=5743, DisplayValue='DOT(1) - Ensure Defense Transportation Infrastructure', PK_PicklistType=447, SortOrder=51)
,(UsageCode='DOT_2_RESPSRUPT',PK_PickList=5744, DisplayValue='DOT(2) - Respond to Transportation Disruptions', PK_PicklistType=447, SortOrder=52)
,(UsageCode='DOT_3_OPERYSTEM',PK_PickList=5745, DisplayValue='DOT(3) - Operate the National Airspace System', PK_PicklistType=447, SortOrder=53)
,(UsageCode='HHS_1_MONI_RISK',PK_PickList=5746, DisplayValue='HHS(1) - Monitor and Respond to Health Emergencies and Risks', PK_PicklistType=447, SortOrder=54)
,(UsageCode='HHS_2_OVERODUCT',PK_PickList=5747, DisplayValue='HHS(2) - Oversee Safety of Medical and Food Products', PK_PicklistType=447, SortOrder=55)
,(UsageCode='HHS_3_PROVERVIC',PK_PickList=5748, DisplayValue='HHS(3) - Provide Medical Care and Services', PK_PicklistType=447, SortOrder=56)
,(UsageCode='NRC_1_MAINEVENT',PK_PickList=5749, DisplayValue='NRC(1) - Maintain Awareness and Respond to U.S. Civilian Nuclear Events', PK_PicklistType=447, SortOrder=57)
,(UsageCode='NRC_2_ENSU_OPER',PK_PickList=5750, DisplayValue='NRC(2) - Ensure Safe U.S. Civilian Nuclear Operations', PK_PicklistType=447, SortOrder=58)
,(UsageCode='FCC_1_MAINOMMUN',PK_PickList=5751, DisplayValue='FCC(1) - Maintain Operational Communications', PK_PicklistType=447, SortOrder=59)
,(UsageCode='EPA_1_RESPHREAT',PK_PickList=5752, DisplayValue='EPA(1) - Respond to Environmental and Health Threats', PK_PicklistType=447, SortOrder=60)
,(UsageCode='CFTC_1_MONARKET',PK_PickList=5753, DisplayValue='CFTC(1) - Monitor Commodity Futures Markets', PK_PicklistType=447, SortOrder=61)
,(UsageCode='SSA_1_PROVERVIC',PK_PickList=5754, DisplayValue='SSA(1) - Provide Social Security Services', PK_PicklistType=447, SortOrder=62)
,(UsageCode='SEC_1_REGUARKET',PK_PickList=5755, DisplayValue='SEC(1) - Regulate Securities Markets', PK_PicklistType=447, SortOrder=63)
,(UsageCode='OPM_1_PROVERVIC',PK_PickList=5756, DisplayValue='OPM(1) - Provide Human Capital Services', PK_PicklistType=447, SortOrder=64)
,(UsageCode='NASA_1_OPER_SAT',PK_PickList=5757, DisplayValue='NASA(1) - Operate Satellites', PK_PicklistType=447, SortOrder=65)
,(UsageCode='VA_1_PROVI_CARE',PK_PickList=5758, DisplayValue='VA(1) - Provide Medical Care', PK_PicklistType=447, SortOrder=66)
,(UsageCode='ODNI_1_COLELLIG',PK_PickList=5759, DisplayValue='ODNI(1) - Collect, Analyze, and Provide Intelligence', PK_PicklistType=447, SortOrder=67)
,(UsageCode='NARA_1_PUBEGIST',PK_PickList=5760, DisplayValue='NARA(1) - Publish the Federal Register', PK_PicklistType=447, SortOrder=68)
,(UsageCode='USPS_1_DELERVIC',PK_PickList=5761, DisplayValue='USPS(1) - Deliver Postal Services', PK_PicklistType=447, SortOrder=69)
,(UsageCode='NCUA_1_MAIUNION',PK_PickList=5762, DisplayValue='NCUA(1) - Maintain Solvent Credit Unions', PK_PicklistType=447, SortOrder=70)
,(UsageCode='N_1_YE',PK_PickList=5772, DisplayValue=' Yes', PK_PicklistType=448, SortOrder=1)
,(UsageCode='N_2_NO',PK_PickList=5773, DisplayValue=' No', PK_PicklistType=448, SortOrder=2)
,(UsageCode='N_3_UNKNOWN',PK_PickList=5774, DisplayValue=' Unknown', PK_PicklistType=448, SortOrder=3)
,(UsageCode='N_1_INTEG',PK_PickList=5784, DisplayValue=' Integer', PK_PicklistType=449, SortOrder=1)
,(UsageCode='N_1_FREE_TEXT',PK_PickList=5794, DisplayValue=' Free Text', PK_PicklistType=450, SortOrder=1)
,(UsageCode='N_1_HVA_SUF_MEF',PK_PickList=5804, DisplayValue=' HVA does not support a PMEF or MEF. ', PK_PicklistType=451, SortOrder=1)
,(UsageCode='N_2_NO_IMPENDED',PK_PickList=5805, DisplayValue=' No impact: Essential function is accomplished as intended.', PK_PicklistType=451, SortOrder=2)
,(UsageCode='N_3_WORK_AKNOWS',PK_PickList=5806, DisplayValue=' Work around: Essential function is still fully accomplished but requires documented and trained-to work around procedures. "Workaround” does not mean patched together actions or “hacks.”  Defined as approved, documented plans that staff already knows. ', PK_PicklistType=451, SortOrder=3)
,(UsageCode='N_4_DEGRADVIDED',PK_PickList=5807, DisplayValue=' Degraded: Essential function is partially accomplished.  There may be delays in time. There may be omissions of information. There may be parts of functions that cannot be provided.', PK_PicklistType=451, SortOrder=4)
,(UsageCode='N_5_FAILURGENCY',PK_PickList=5808, DisplayValue=' Failure: Essential function cannot be accomplished.  Highest impact to mission and function of Agency.', PK_PicklistType=451, SortOrder=5)
,(UsageCode='N_1_SAFETI',PK_PickList=5818, DisplayValue=' Safety', PK_PicklistType=452, SortOrder=1)
,(UsageCode='N_2_ENVIRONMENT',PK_PickList=5819, DisplayValue=' Environmental', PK_PicklistType=452, SortOrder=2)
,(UsageCode='N_3_FINANCI',PK_PickList=5820, DisplayValue=' Financial', PK_PicklistType=452, SortOrder=3)
,(UsageCode='N_4_PUBLIC_TRUS',PK_PickList=5821, DisplayValue=' Public Trust', PK_PicklistType=452, SortOrder=4)
,(UsageCode='N_5_OTHER_FREE_',PK_PickList=5822, DisplayValue=' Other [Free Text]', PK_PicklistType=452, SortOrder=5)
,(UsageCode='N_1_YE',PK_PickList=5832, DisplayValue=' Yes', PK_PicklistType=453, SortOrder=1)
,(UsageCode='N_2_NO',PK_PickList=5833, DisplayValue=' No', PK_PicklistType=453, SortOrder=2)
,(UsageCode='N_3_UNKNOWN',PK_PickList=5834, DisplayValue=' Unknown', PK_PicklistType=453, SortOrder=3)
,(UsageCode='N_1_YE',PK_PickList=5844, DisplayValue=' Yes', PK_PicklistType=454, SortOrder=1)
,(UsageCode='N_2_NO',PK_PickList=5845, DisplayValue=' No', PK_PicklistType=454, SortOrder=2)
,(UsageCode='N_3_UNKNOWN',PK_PickList=5846, DisplayValue=' Unknown', PK_PicklistType=454, SortOrder=3)
,(UsageCode='N_1_PII',PK_PickList=5856, DisplayValue=' PII', PK_PicklistType=455, SortOrder=1)
,(UsageCode='N_2_PHI',PK_PickList=5857, DisplayValue=' PHI', PK_PicklistType=455, SortOrder=2)
,(UsageCode='N_3_LAW_ENFORC',PK_PickList=5858, DisplayValue=' Law Enforcement', PK_PicklistType=455, SortOrder=3)
,(UsageCode='N_4_PRE_RELEAS',PK_PickList=5859, DisplayValue=' Pre-Release', PK_PicklistType=455, SortOrder=4)
,(UsageCode='N_5_IP',PK_PickList=5860, DisplayValue=' IP', PK_PicklistType=455, SortOrder=5)
,(UsageCode='N_6_OTHER_FREE_',PK_PickList=5861, DisplayValue=' Other [Free Text]', PK_PicklistType=455, SortOrder=6)
,(UsageCode='N_1K',PK_PickList=5871, DisplayValue='<1K', PK_PicklistType=456, SortOrder=1)
,(UsageCode='N_1K_100K',PK_PickList=5872, DisplayValue='1K - 100K', PK_PicklistType=456, SortOrder=2)
,(UsageCode='N_100K_1M',PK_PickList=5873, DisplayValue='100K -1M', PK_PicklistType=456, SortOrder=3)
,(UsageCode='N_1M_100M',PK_PickList=5874, DisplayValue='1M - 100M', PK_PicklistType=456, SortOrder=4)
,(UsageCode='N_100M',PK_PickList=5875, DisplayValue='> 100M', PK_PicklistType=456, SortOrder=5)
,(UsageCode='UNKNOWN',PK_PickList=5876, DisplayValue='Unknown', PK_PicklistType=456, SortOrder=6)
,(UsageCode='N_A',PK_PickList=5877, DisplayValue='nan', PK_PicklistType=456, SortOrder=7)
,(UsageCode='N_1K',PK_PickList=5887, DisplayValue='<1K', PK_PicklistType=457, SortOrder=1)
,(UsageCode='N_1K_100K',PK_PickList=5888, DisplayValue='1K - 100K', PK_PicklistType=457, SortOrder=2)
,(UsageCode='N_100K_1M',PK_PickList=5889, DisplayValue='100K -1M', PK_PicklistType=457, SortOrder=3)
,(UsageCode='N_1M_100M',PK_PickList=5890, DisplayValue='1M - 100M', PK_PicklistType=457, SortOrder=4)
,(UsageCode='N_100M',PK_PickList=5891, DisplayValue='> 100M', PK_PicklistType=457, SortOrder=5)
,(UsageCode='UNKNOWN',PK_PickList=5892, DisplayValue='Unknown', PK_PicklistType=457, SortOrder=6)
,(UsageCode='N_A',PK_PickList=5893, DisplayValue='nan', PK_PicklistType=457, SortOrder=7)
,(UsageCode='N_1K',PK_PickList=5903, DisplayValue='<1K', PK_PicklistType=458, SortOrder=1)
,(UsageCode='N_1K_100K',PK_PickList=5904, DisplayValue='1K - 100K', PK_PicklistType=458, SortOrder=2)
,(UsageCode='N_100K_1M',PK_PickList=5905, DisplayValue='100K -1M', PK_PicklistType=458, SortOrder=3)
,(UsageCode='N_1M_100M',PK_PickList=5906, DisplayValue='1M - 100M', PK_PicklistType=458, SortOrder=4)
,(UsageCode='N_100M',PK_PickList=5907, DisplayValue='> 100M', PK_PicklistType=458, SortOrder=5)
,(UsageCode='UNKNOWN',PK_PickList=5908, DisplayValue='Unknown', PK_PicklistType=458, SortOrder=6)
,(UsageCode='N_A',PK_PickList=5909, DisplayValue='nan', PK_PicklistType=458, SortOrder=7)
,(UsageCode='N_1K',PK_PickList=5919, DisplayValue='<1K', PK_PicklistType=459, SortOrder=1)
,(UsageCode='N_1K_100K',PK_PickList=5920, DisplayValue='1K - 100K', PK_PicklistType=459, SortOrder=2)
,(UsageCode='N_100K_1M',PK_PickList=5921, DisplayValue='100K -1M', PK_PicklistType=459, SortOrder=3)
,(UsageCode='N_1M_100M',PK_PickList=5922, DisplayValue='1M - 100M', PK_PicklistType=459, SortOrder=4)
,(UsageCode='N_100M',PK_PickList=5923, DisplayValue='> 100M', PK_PicklistType=459, SortOrder=5)
,(UsageCode='UNKNOWN',PK_PickList=5924, DisplayValue='Unknown', PK_PicklistType=459, SortOrder=6)
,(UsageCode='N_A',PK_PickList=5925, DisplayValue='nan', PK_PicklistType=459, SortOrder=7)
,(UsageCode='N_1K',PK_PickList=5935, DisplayValue='<1K', PK_PicklistType=460, SortOrder=1)
,(UsageCode='N_1K_100K',PK_PickList=5936, DisplayValue='1K - 100K', PK_PicklistType=460, SortOrder=2)
,(UsageCode='N_100K_1M',PK_PickList=5937, DisplayValue='100K -1M', PK_PicklistType=460, SortOrder=3)
,(UsageCode='N_1M_100M',PK_PickList=5938, DisplayValue='1M - 100M', PK_PicklistType=460, SortOrder=4)
,(UsageCode='N_100M',PK_PickList=5939, DisplayValue='> 100M', PK_PicklistType=460, SortOrder=5)
,(UsageCode='UNKNOWN',PK_PickList=5940, DisplayValue='Unknown', PK_PicklistType=460, SortOrder=6)
,(UsageCode='N_A',PK_PickList=5941, DisplayValue='nan', PK_PicklistType=460, SortOrder=7)
,(UsageCode='N_1K',PK_PickList=5951, DisplayValue='<1K', PK_PicklistType=461, SortOrder=1)
,(UsageCode='N_1K_100K',PK_PickList=5952, DisplayValue='1K - 100K', PK_PicklistType=461, SortOrder=2)
,(UsageCode='N_100K_1M',PK_PickList=5953, DisplayValue='100K -1M', PK_PicklistType=461, SortOrder=3)
,(UsageCode='N_1M_100M',PK_PickList=5954, DisplayValue='1M - 100M', PK_PicklistType=461, SortOrder=4)
,(UsageCode='N_100M',PK_PickList=5955, DisplayValue='> 100M', PK_PicklistType=461, SortOrder=5)
,(UsageCode='UNKNOWN',PK_PickList=5956, DisplayValue='Unknown', PK_PicklistType=461, SortOrder=6)
,(UsageCode='N_A',PK_PickList=5957, DisplayValue='nan', PK_PicklistType=461, SortOrder=7)
,(UsageCode='N_1K',PK_PickList=5967, DisplayValue='<1K', PK_PicklistType=462, SortOrder=1)
,(UsageCode='N_1K_100K',PK_PickList=5968, DisplayValue='1K - 100K', PK_PicklistType=462, SortOrder=2)
,(UsageCode='N_100K_1M',PK_PickList=5969, DisplayValue='100K -1M', PK_PicklistType=462, SortOrder=3)
,(UsageCode='N_1M_100M',PK_PickList=5970, DisplayValue='1M - 100M', PK_PicklistType=462, SortOrder=4)
,(UsageCode='N_100M',PK_PickList=5971, DisplayValue='> 100M', PK_PicklistType=462, SortOrder=5)
,(UsageCode='UNKNOWN',PK_PickList=5972, DisplayValue='Unknown', PK_PicklistType=462, SortOrder=6)
,(UsageCode='N_A',PK_PickList=5973, DisplayValue='nan', PK_PicklistType=462, SortOrder=7)
,(UsageCode='N_1K',PK_PickList=5983, DisplayValue='<1K', PK_PicklistType=463, SortOrder=1)
,(UsageCode='N_1K_100K',PK_PickList=5984, DisplayValue='1K - 100K', PK_PicklistType=463, SortOrder=2)
,(UsageCode='N_100K_1M',PK_PickList=5985, DisplayValue='100K -1M', PK_PicklistType=463, SortOrder=3)
,(UsageCode='N_1M_100M',PK_PickList=5986, DisplayValue='1M - 100M', PK_PicklistType=463, SortOrder=4)
,(UsageCode='N_100M',PK_PickList=5987, DisplayValue='> 100M', PK_PicklistType=463, SortOrder=5)
,(UsageCode='UNKNOWN',PK_PickList=5988, DisplayValue='Unknown', PK_PicklistType=463, SortOrder=6)
,(UsageCode='N_A',PK_PickList=5989, DisplayValue='nan', PK_PicklistType=463, SortOrder=7)
,(UsageCode='N_1K',PK_PickList=5999, DisplayValue='<1K', PK_PicklistType=464, SortOrder=1)
,(UsageCode='N_1K_100K',PK_PickList=6000, DisplayValue='1K - 100K', PK_PicklistType=464, SortOrder=2)
,(UsageCode='N_100K_1M',PK_PickList=6001, DisplayValue='100K -1M', PK_PicklistType=464, SortOrder=3)
,(UsageCode='N_1M_100M',PK_PickList=6002, DisplayValue='1M - 100M', PK_PicklistType=464, SortOrder=4)
,(UsageCode='N_100M',PK_PickList=6003, DisplayValue='> 100M', PK_PicklistType=464, SortOrder=5)
,(UsageCode='UNKNOWN',PK_PickList=6004, DisplayValue='Unknown', PK_PicklistType=464, SortOrder=6)
,(UsageCode='N_A',PK_PickList=6005, DisplayValue='nan', PK_PicklistType=464, SortOrder=7)
,(UsageCode='N_1K',PK_PickList=6015, DisplayValue='<1K', PK_PicklistType=465, SortOrder=1)
,(UsageCode='N_1K_100K',PK_PickList=6016, DisplayValue='1K - 100K', PK_PicklistType=465, SortOrder=2)
,(UsageCode='N_100K_1M',PK_PickList=6017, DisplayValue='100K -1M', PK_PicklistType=465, SortOrder=3)
,(UsageCode='N_1M_100M',PK_PickList=6018, DisplayValue='1M - 100M', PK_PicklistType=465, SortOrder=4)
,(UsageCode='N_100M',PK_PickList=6019, DisplayValue='> 100M', PK_PicklistType=465, SortOrder=5)
,(UsageCode='UNKNOWN',PK_PickList=6020, DisplayValue='Unknown', PK_PicklistType=465, SortOrder=6)
,(UsageCode='N_A',PK_PickList=6021, DisplayValue='nan', PK_PicklistType=465, SortOrder=7)
,(UsageCode='N_1K',PK_PickList=6031, DisplayValue='<1K', PK_PicklistType=466, SortOrder=1)
,(UsageCode='N_1K_100K',PK_PickList=6032, DisplayValue='1K - 100K', PK_PicklistType=466, SortOrder=2)
,(UsageCode='N_100K_1M',PK_PickList=6033, DisplayValue='100K -1M', PK_PicklistType=466, SortOrder=3)
,(UsageCode='N_1M_100M',PK_PickList=6034, DisplayValue='1M - 100M', PK_PicklistType=466, SortOrder=4)
,(UsageCode='N_100M',PK_PickList=6035, DisplayValue='> 100M', PK_PicklistType=466, SortOrder=5)
,(UsageCode='UNKNOWN',PK_PickList=6036, DisplayValue='Unknown', PK_PicklistType=466, SortOrder=6)
,(UsageCode='N_A',PK_PickList=6037, DisplayValue='nan', PK_PicklistType=466, SortOrder=7)
,(UsageCode='N_1_FREE_TEXT',PK_PickList=6047, DisplayValue=' Free Text', PK_PicklistType=467, SortOrder=1)
,(UsageCode='N_1_10',PK_PickList=6057, DisplayValue='1-10', PK_PicklistType=468, SortOrder=1)
,(UsageCode='N_11_25',PK_PickList=6058, DisplayValue='11-25', PK_PicklistType=468, SortOrder=2)
,(UsageCode='N_26_50',PK_PickList=6059, DisplayValue='26-50', PK_PicklistType=468, SortOrder=3)
,(UsageCode='N_51_200',PK_PickList=6060, DisplayValue='51-200', PK_PicklistType=468, SortOrder=4)
,(UsageCode='N_201',PK_PickList=6061, DisplayValue=' 201+', PK_PicklistType=468, SortOrder=5)
,(UsageCode='N_1_FREE_TEXT',PK_PickList=6071, DisplayValue=' Free text', PK_PicklistType=469, SortOrder=1)
,(UsageCode='N_1_FREE_TEXT',PK_PickList=6081, DisplayValue=' Free text', PK_PicklistType=470, SortOrder=1)
,(UsageCode='N_1_FREE_TEXT',PK_PickList=6082, DisplayValue=' Free text', PK_PicklistType=470, SortOrder=2)
,(UsageCode='N_1_YE',PK_PickList=6092, DisplayValue=' Yes', PK_PicklistType=471, SortOrder=1)
,(UsageCode='N_2_NO',PK_PickList=6093, DisplayValue=' No', PK_PicklistType=471, SortOrder=2)
,(UsageCode='N_3_UNKNOWN',PK_PickList=6094, DisplayValue=' Unknown', PK_PicklistType=471, SortOrder=3)
,(UsageCode='N_1_YE',PK_PickList=6104, DisplayValue=' Yes', PK_PicklistType=472, SortOrder=1)
,(UsageCode='N_2_NO',PK_PickList=6105, DisplayValue=' No', PK_PicklistType=472, SortOrder=2)
,(UsageCode='N_3_UNKNOWN',PK_PickList=6106, DisplayValue=' Unknown', PK_PicklistType=472, SortOrder=3)
,(UsageCode='N_1_YE',PK_PickList=6116, DisplayValue=' Yes', PK_PicklistType=473, SortOrder=1)
,(UsageCode='N_2_NO',PK_PickList=6117, DisplayValue=' No', PK_PicklistType=473, SortOrder=2)
,(UsageCode='N_3_UNKNOWN',PK_PickList=6118, DisplayValue=' Unknown', PK_PicklistType=473, SortOrder=3)
,(UsageCode='N_1_YE',PK_PickList=6128, DisplayValue=' Yes', PK_PicklistType=474, SortOrder=1)
,(UsageCode='N_2_NO',PK_PickList=6129, DisplayValue=' No', PK_PicklistType=474, SortOrder=2)
,(UsageCode='N_3_UNKNOWN',PK_PickList=6130, DisplayValue=' Unknown', PK_PicklistType=474, SortOrder=3)
,(UsageCode='N_1_TRANSMIT',PK_PickList=6140, DisplayValue=' Transmit', PK_PicklistType=475, SortOrder=1)
,(UsageCode='N_2_RECEIV',PK_PickList=6141, DisplayValue=' Receive', PK_PicklistType=475, SortOrder=2)
,(UsageCode='N_3_BOTH',PK_PickList=6142, DisplayValue=' Both', PK_PicklistType=475, SortOrder=3)
,(UsageCode='N_1_FREE_TEXT',PK_PickList=6152, DisplayValue=' Free Text', PK_PicklistType=476, SortOrder=1)
,(UsageCode='N_1_FREE_TEXT',PK_PickList=6162, DisplayValue=' Free Text', PK_PicklistType=477, SortOrder=1)
,(UsageCode='N_1_FREE_TEXT',PK_PickList=6172, DisplayValue=' Free Text', PK_PicklistType=478, SortOrder=1)
,(UsageCode='N_1_PRIVATE_COM',PK_PickList=6182, DisplayValue=' Private/Commercial', PK_PicklistType=479, SortOrder=1)
,(UsageCode='N_2_NGO',PK_PickList=6183, DisplayValue=' NGO', PK_PicklistType=479, SortOrder=2)
,(UsageCode='N_3_FFRDC',PK_PickList=6184, DisplayValue=' FFRDC', PK_PicklistType=479, SortOrder=3)
,(UsageCode='N_4_SLTT',PK_PickList=6185, DisplayValue=' SLTT', PK_PicklistType=479, SortOrder=4)
,(UsageCode='N_5_OTHER',PK_PickList=6186, DisplayValue=' Other', PK_PicklistType=479, SortOrder=5)
,(UsageCode='N_1_YE',PK_PickList=6196, DisplayValue=' Yes', PK_PicklistType=480, SortOrder=1)
,(UsageCode='N_2_NO',PK_PickList=6197, DisplayValue=' No', PK_PicklistType=480, SortOrder=2)
,(UsageCode='N_3_UNKNOWN',PK_PickList=6198, DisplayValue=' Unknown', PK_PicklistType=480, SortOrder=3)
,(UsageCode='N_1_YE',PK_PickList=6208, DisplayValue=' Yes', PK_PicklistType=481, SortOrder=1)
,(UsageCode='N_2_NO',PK_PickList=6209, DisplayValue=' No', PK_PicklistType=481, SortOrder=2)
,(UsageCode='N_3_UNKNOWN',PK_PickList=6210, DisplayValue=' Unknown', PK_PicklistType=481, SortOrder=3)
,(UsageCode='N_1_YE',PK_PickList=6220, DisplayValue=' Yes', PK_PicklistType=482, SortOrder=1)
,(UsageCode='N_2_NO',PK_PickList=6221, DisplayValue=' No', PK_PicklistType=482, SortOrder=2)
,(UsageCode='N_3_UNKNOWN',PK_PickList=6222, DisplayValue=' Unknown', PK_PicklistType=482, SortOrder=3)
,(UsageCode='N_1_TRANSMIT',PK_PickList=6232, DisplayValue=' Transmit', PK_PicklistType=483, SortOrder=1)
,(UsageCode='N_2_RECEIV',PK_PickList=6233, DisplayValue=' Receive', PK_PicklistType=483, SortOrder=2)
,(UsageCode='N_3_BOTH',PK_PickList=6234, DisplayValue=' Both', PK_PicklistType=483, SortOrder=3)
