'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _{classname}

    '''<summary>
    '''Panel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''CBlabelGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBlabelGroup As Global.CyberScope.CustomControls_CBlabel

    '''<summary>
    '''lblError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CBlabel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBlabel2 As Global.CyberScope.CustomControls_CBlabel

    '''<summary>
    '''CBlabel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBlabel3 As Global.CyberScope.CustomControls_CBlabel

    '''<summary>
    '''lblInfo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInfo1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CBPicklist2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBPicklist2 As Global.CyberScope.CustomControls_CBpicklist2

    '''<summary>
    '''CBoptionalLinks1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBoptionalLinks1 As Global.CyberScope.CustomControls_CBoptionalLinks

    '''<summary>
    '''CBlabel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBlabel4 As Global.CyberScope.CustomControls_CBlabel

    '''<summary>
    '''CBlabel5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBlabel5 As Global.CyberScope.CustomControls_CBlabel

    '''<summary>
    '''lblInfo2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInfo2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CBPicklist3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBPicklist3 As Global.CyberScope.CustomControls_CBpicklist2

    '''<summary>
    '''CBoptionalLinks2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBoptionalLinks2 As Global.CyberScope.CustomControls_CBoptionalLinks

    '''<summary>
    '''CBlabel6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBlabel6 As Global.CyberScope.CustomControls_CBlabel

    '''<summary>
    '''CBlabel7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBlabel7 As Global.CyberScope.CustomControls_CBlabel

    '''<summary>
    '''lblInfo3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInfo3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CBPicklist4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBPicklist4 As Global.CyberScope.CustomControls_CBpicklist2

    '''<summary>
    '''CBoptionalLinks3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBoptionalLinks3 As Global.CyberScope.CustomControls_CBoptionalLinks

    '''<summary>
    '''CBlabel8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBlabel8 As Global.CyberScope.CustomControls_CBlabel

    '''<summary>
    '''CBlabel9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBlabel9 As Global.CyberScope.CustomControls_CBlabel

    '''<summary>
    '''lblInfo4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInfo4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CBPicklist5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBPicklist5 As Global.CyberScope.CustomControls_CBpicklist2

    '''<summary>
    '''CBoptionalLinks4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBoptionalLinks4 As Global.CyberScope.CustomControls_CBoptionalLinks

    '''<summary>
    '''CBlabel10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBlabel10 As Global.CyberScope.CustomControls_CBlabel

    '''<summary>
    '''CBlabel11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBlabel11 As Global.CyberScope.CustomControls_CBlabel

    '''<summary>
    '''lblInfo5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInfo5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CBPicklist6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBPicklist6 As Global.CyberScope.CustomControls_CBpicklist2

    '''<summary>
    '''CBoptionalLinks5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBoptionalLinks5 As Global.CyberScope.CustomControls_CBoptionalLinks

    '''<summary>
    '''CBlabel12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBlabel12 As Global.CyberScope.CustomControls_CBlabel

    '''<summary>
    '''CBlabel13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBlabel13 As Global.CyberScope.CustomControls_CBlabel

    '''<summary>
    '''lblInfo6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInfo6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CBPicklist7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBPicklist7 As Global.CyberScope.CustomControls_CBpicklist2

    '''<summary>
    '''CBoptionalLinks6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBoptionalLinks6 As Global.CyberScope.CustomControls_CBoptionalLinks

    '''<summary>
    '''CBlabel14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBlabel14 As Global.CyberScope.CustomControls_CBlabel

    '''<summary>
    '''CBlabel15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBlabel15 As Global.CyberScope.CustomControls_CBlabel

    '''<summary>
    '''lblInfo7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInfo7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CBPicklist8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBPicklist8 As Global.CyberScope.CustomControls_CBpicklist2

    '''<summary>
    '''CBoptionalLinks7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBoptionalLinks7 As Global.CyberScope.CustomControls_CBoptionalLinks

    '''<summary>
    '''CBlabel16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBlabel16 As Global.CyberScope.CustomControls_CBlabel

    '''<summary>
    '''CBlabel17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBlabel17 As Global.CyberScope.CustomControls_CBlabel

    '''<summary>
    '''lblInfo8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInfo8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CBPicklist9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBPicklist9 As Global.CyberScope.CustomControls_CBpicklist2

    '''<summary>
    '''CBoptionalLinks8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBoptionalLinks8 As Global.CyberScope.CustomControls_CBoptionalLinks

    '''<summary>
    '''CBlabel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBlabel1 As Global.CyberScope.CustomControls_CBlabel

    '''<summary>
    '''CBlabel18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBlabel18 As Global.CyberScope.CustomControls_CBlabel

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CBPicklist1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBPicklist1 As Global.CyberScope.CustomControls_CBpicklist2

    '''<summary>
    '''CBoptionalLinks9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBoptionalLinks9 As Global.CyberScope.CustomControls_CBoptionalLinks

    '''<summary>
    '''CBlabel29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBlabel29 As Global.CyberScope.CustomControls_CBlabel

    '''<summary>
    '''CBlabel30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBlabel30 As Global.CyberScope.CustomControls_CBlabel

    '''<summary>
    '''CBtext1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBtext1 As Global.CyberScope.CustomControls_CBtext2

    '''<summary>
    '''CBoptionalLinks15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBoptionalLinks15 As Global.CyberScope.CustomControls_CBoptionalLinks

    '''<summary>
    '''CBButtPanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CBButtPanel1 As Global.CyberScope.CustomControls_CBButtPanel2
End Class
